<template lang="pug">
section#project
	h1.title projects
	div.tagline Want to see more projects? 
		a(v-scroll-to="'#contact'") Contact Me!
	div.card-container
		div.card(v-for="project in projectList")
			div.img-wrapper
				img(:src="project.img")
			h2.item-title {{ project.title }}
			p {{ project.description }}
			div
				a(:href="project.link") Check out
</template>

<script>
export default {
	data(){
		return {
			projectList: [{
				img: '/assets/wriget.png',
				title: 'Wriget',
				description: 'Founder and Developer of app dedicated to making writing easier by giving authors a central database to store their characters, worlds, plots, etc. as well as interactive visualization.',
				link: 'http://wriget.com'
			}, {
				img: '/assets/cssart.png',
				title: 'Css Art',
				description: 'One day I decided I wanted to get better at CSS, so I began to translate cartoon images into HTML and CSS3 pseudo elements. Some images are also animated/randomly generated by Javascript.',
				link: '/cssart/cssart.html'
			}, {
				img: '/assets/santos.png',
				title: 'Santos Family Foundation',
				description: 'The Santos Family Foundation is dedicated to improving vehicular safety for all road users. As part of that mission that have partnered with Olin College in funding a SCOPE team. This is a team of four college seniors working to make a huge impact on the way we look at road safety.',
				link: 'http://santosfoundationscope.github.io/'
			}]
		}
	}
}
</script>

<style lang="scss">

$lightblue: #40798C;

#project {
	min-height: 100%;

	.card-container {
		display: flex;
		flex-wrap: wrap;
		justify-content: center;
	}

	.card {
		display: flex;
		width: calc(100% * (1/3) - 10px - 1px);
		flex-direction: column;
		min-width: 300px;
    	margin-bottom: 1em;

		.img-wrapper {
			width: 100%;
			text-align: center;
		}

		img {
			max-width: 100%;
		}

		p {
			padding: 1em;
		}

		a {
			font-family: 'Montserrat', Arial, sans-serif;
			padding: 5px;
		    border-radius: 15px;
		    color: $lightblue;
		    border: 1px solid $lightblue;

		    &:hover {
		    	opacity: 1;
		    	background: $lightblue;
    			color: white;
		    }
		}
	}
}

</style>